### ISSUE TITLE
providing additional shell scripts to help preparations

### ISSUE THREAD

**Issue by jjuod** [william-denault/WaveletScreaming#3]
Got some wrappers and shell scripts that are useful, e.g. automatic parallel VCF slicing and conversion. Not sure how they could be distributed - possibly an `examples/` folder?

**Comment by william-denault** [comment]
Completely agree on that i would give a lot of added value to the package

**Comment by jjuod** [comment]
Working version is provided in commit a428b969c930336821a2b3046fa0508326a69c14
