### ISSUE TITLE
Reported coverage not entirely correct

### ISSUE THREAD

**Issue by jjuod** [william-denault/WaveletScreaming#4]
Coverage of slices reported by `slice_definition()` has problems:
1. does not correspond to coverage of SNPs - it calculates size of covered region in bp, and SNP density is not equal everywhere
2. does not exactly correspond to coverage of positions, because it takes smallest and largest positions of observed markers as chromosome ends (and closest markers can be as far as 25 Mbp from actual ends).
3. Coverage is only printed out, and not stored anywhere.

Should improve if deemed important.

**Comment by william-denault** [comment]
Corrected
